version: "3"

services:
  server-database:
    container_name: db
    image: mysql:5.6
    build: ./db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/data/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database



  client:
    container_name: docker-vue
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    links:
      - server-database
    depends_on:
      - server


  server:
    container_name: docker-node-final
    restart: on-failure
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    links:
      - server-database
    depends_on:
      - server-database







